### ISSUE TITLE
Notifications through flatpak do not work

### ISSUE THREAD

**Issue by toastxc** [hoodie/notify-rust#205]
Hi,
After installing various dependancies for Ubuntu notifications started to work (yay), although weirdly they did not come through the default GNOME interface, but that is an issue for another time.

The issue I have is that despite enabling every permission possible on flatseal (Dbus and all) notifications simply don't work.
`org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`
NOTE: it is possible that this issue is a user error, as there may be more steps needed for flatpak.

## Steps to reproduce
```bash
# clone the repository
git clone https://github.com/toastxc/kuma-rs.git
# cargo-pak manages flatpaks for rust apps, its safe dw
cargo install cargo-pak
cd kuma-rs/
# this uses cargo-pak
sh install.sh
flatpak run xyz.toastxc.Kuma
```

**Comment by toastxc** [comment]
huh... enabling this in flatseal does not fix the issue, it only works from fixing the flatpak manifest which is odd.

Problem solved

```toml
app_id="xyz.toastxc.Kuma"
app_name="Kuma"
profile="release"
bin="gui"
permissions = [
    "--share=network",
    "--socket=x11",
    "--device=dri",
    "--socket=system-bus",
    "--socket=session-bus",
    "--filesystem=host"
]

[desktopfile]
terminal= false
```
