### ISSUE TITLE
Notifications randomly don't appear on Windows

### ISSUE THREAD

**Issue by MCluck90** [hoodie/notify-rust#79]
Most of the time notifications get sent out but occasionally they don't. There doesn't seem to be any relation with how quickly they're sent out. I've tested seconds apart and as much as 20 minutes apart. No errors are reported.

## MCVE

```toml
# Cargo.toml
[package]
name = "pomo"
version = "0.1.0"
edition = "2018"

[dependencies]
notify-rust = "4.0.0"
```

```rust
// src/main.rs
use notify_rust::{Notification, Timeout};

fn main() {
    Notification::new()
        .appname("Pomo")
        .summary("Break time!")
        .timeout(Timeout::Milliseconds(6000))
        .show()
        .unwrap();
}
```

* **OS**: Windows 10
* **rustc**: 1.44.1
